### ISSUE TITLE
NodeState struct visibility

### ISSUE THREAD

**Issue by r3bu1ld3r** [quickwit-oss/chitchat#57]
Hello, @fulmicoton !
Could you please explain, why are you keeping `NodeState` structure private while `ClusterState`'s methods
```rust
pub fn node_state(&self, node_id: &NodeId) -> Option<&NodeState> {..}
pub fn node_state_mut(&mut self, node_id: &NodeId) -> &mut NodeState  {..}
```
return `NodeState` as a result?

Thank you!

**Comment by fulmicoton** [comment]
Well I think this is a mistake! :)
