### ISSUE TITLE
Parameter `marked_for_deletion_grace_period` needs to be reviewed

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/chitchat#81]
Currently, we use `marked_for_deletion_grace_period` to set a deletion grace period expressed as a number of version.

This means two things:
1) an old node that did not communicate with other nodes will have its `max_version` very low compared to others. If  `node_1.max_version + marked_for_deletion_grace_period < node_state.max_version`, we will reset the node state of `node_1`.
2) a key marked for deletion will be deleted if `versioned_value.version + marked_for_deletion_grace_period < max_version`.

But this logic is flawed. If we set `n` keys in a given node... the max_version will in at least `n`. And this is a big issue as now the garbage collection can happen way faster than a user expects.

We can do two things:
- separate the heartbeat version from other keys. So this parameter can be used safely for case 1)
- and now we still need to handle the GC of keys marked for deletion. I'm not sure what we should do. Setting a high value could be good enough.

**Comment by guilload** [comment]
Closed via #84.
